src/main/java/seedu/duke/Parser.java

Add Parser class

---

.gitignore
src/main/java/seedu/duke/Event.java
src/main/java/seedu/duke/EventList.java
src/main/java/seedu/duke/NPExceptions.java
src/main/java/seedu/duke/Parser.java

finished Event and EventList apart from reviseTime function.

Event class

---

build.gradle
src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/storage/Storage.java
src/test/java/seedu/duke/storage/StorageTest.java

Implement saving and loading features using gson
Add JUnit test for Storage

Add Storage class and StorageTest JUnit test

---

build.gradle
src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Event.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/storage/EventListAdapter.java
src/main/java/seedu/duke/storage/Storage.java

Gson TypeAdapter had unsuppressable warnings on loading/saving from json file. 
Storage was integrated to save when quitting the app.
resolves #6

Implement EventListAdapter to serialize/deserialize EventList class & Integrate saving feature

---

src/test/java/seedu/duke/EventListTest.java
src/test/java/seedu/duke/ParserTest.java

Add JUnit tests for Parser and EventList

---

src/main/java/seedu/duke/Parser.java

Fix editing using index & show edit success message

Fix edit index

---

docs/UserGuide.md
src/main/java/seedu/duke/Parser.java

St comp in edit

---

src/main/java/seedu/duke/EventList.java
src/main/java/seedu/duke/Parser.java

found the editing with name was not working (always find and edit the first event) and now it is fixed and I also added exceptions for case where user didn't input valid flag except -e and -i.
Moreover, now for edit and add, only -sd is strictly required and for now I have tested and haven't seen any related issues.

fixed edit by name and improved the input standard of date and time 

---

src/main/java/seedu/duke/NPExceptions.java
src/main/java/seedu/duke/storage/EventListAdapter.java

Improve defensibility of Storage API.

Storage defence

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/Ui.java

@Team, please add logging to your own functionalities as well 😃

Implemented logger & added logging

---

src/main/java/seedu/duke/storage/EventListAdapter.java
src/main/java/seedu/duke/storage/JsonEventListStorage.java
src/main/java/seedu/duke/storage/StorageManager.java
src/test/java/seedu/duke/storage/StorageManagerTest.java

Improved defensibility of Storage API.

Storage upgrade

---

src/main/java/seedu/duke/UserUtility.java

Initially, the timetable counted recess week as a week.
Fixed, please test.

Fix week for timetable

---

src/main/java/seedu/duke/Parser.java

Fix for timetable to show week 13 modules

Ui timetable fix

---

src/main/java/seedu/duke/Parser.java

Fix bug where moduleCode is not converted to uppercase before being searched leading to module not being found in the hashmap.
Fixes #118

Fix bug in parseAddCommand

---

src/main/java/seedu/duke/EventList.java
src/main/java/seedu/duke/Ui.java
src/main/java/seedu/duke/UserUtility.java
src/test/java/seedu/duke/storage/JsonEventListStorageTest.java
src/test/java/seedu/duke/storage/StorageManagerTest.java

tested case:
1. non-r event conflicts with another non-r event, which is the only event in eventList
2. non-r event conflicts with the only recurring event in eventList
3. recurring event conflicts with another recurring, which is the only event in eventList
**haven't tested cases where there are multiple events in eventList that conflict with the new added one.**

finished confliction check and tested on some cases

---

docs/UserGuide.md
src/main/java/seedu/duke/NusModule.java
src/main/java/seedu/duke/SemData.java
src/main/java/seedu/duke/storage/EventListAdapter.java
src/main/java/seedu/duke/storage/JsonEventListStorage.java
src/main/java/seedu/duke/storage/ModuleAdapter.java
src/main/java/seedu/duke/storage/StorageManager.java
src/test/java/seedu/duke/storage/NusModuleStorageTest.java

Refactor storage to SLAP more. Modified ModuleAdapter to parse nusmods Week objects into week intervals for special term.  
Resolves #144

Storage improvement

---

src/main/java/seedu/duke/storage/EventListAdapter.java

fix bug where event with no start time can be added after modifications to json file.

Fix bug in EventListAdapter

---

src/main/java/seedu/duke/EventList.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/Schedule.java

Refactor contructors in Schedule, write some java doc & add more details in exception message

---

docs/DeveloperGuide.md

Add content page, introduction, instructions for testing, and update appropriate appendices

Update Developer Guide 

---

docs/UserGuide.md
src/main/java/seedu/duke/storage/ModuleAdapter.java
src/test/java/seedu/duke/storage/NusModuleStorageTest.java
src/test/java/seedu/duke/storage/StorageManagerTest.java

Update storage lessonType key to match what is displayed on NUSMODS

Update UG and Storage
